fix: cd workflow

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -16,7 +16,9 @@ jobs:
           username: ${{ secrets.SSH_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
-            # Update package index and install dependencies
+            set -e  # Exit immediately if a command exits with a non-zero status
+
+            # Update and install necessary packages
             sudo apt-get update -y
             sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
 
@@ -41,7 +43,14 @@ jobs:
 
             # Navigate to the project directory and deploy
             cd /home/ubuntu/
-            git clone https://github.com/chukssomzzy/fastapi-book-project
-            cd fastapi-book-project/
-            git pull
+            if [ -d "fastapi-book-project" ]; then
+              cd fastapi-book-project
+              git fetch --all
+              git reset --hard origin/main
+            else
+              git clone https://github.com/chukssomzzy/fastapi-book-project
+              cd fastapi-book-project
+            fi
+
+            # Bring up the Docker containers
             docker-compose up -d --build
